# Generated by Django 5.1.15 on 2026-04-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100, unique=True, verbose_name='기기명')),
                ('token', models.TextField(verbose_name='FCM 토큰')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
            ],
            options={
                'verbose_name': 'FCM 기기 토큰',
                'verbose_name_plural': 'FCM 기기 토큰',
                'db_table': 'device_tokens',
            },
        ),
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='대상명')),
                ('host', models.CharField(max_length=255, verbose_name='호스트')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='포트')),
                ('check_type', models.CharField(choices=[('ping', 'Ping'), ('port', 'Port'), ('http', 'HTTP'), ('resource', 'Resource')], default='ping', max_length=20, verbose_name='체크 타입')),
                ('check_url', models.CharField(blank=True, default='', max_length=500, verbose_name='체크 URL')),
                ('group', models.CharField(choices=[('server', 'Server'), ('service', 'Service'), ('cctv', 'CCTV'), ('router', 'Router')], default='server', max_length=20, verbose_name='그룹')),
                ('interval', models.IntegerField(default=60, verbose_name='체크 주기(초)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('last_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('warn', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='최근 상태')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='마지막 체크')),
                ('last_response_time', models.FloatField(blank=True, null=True, verbose_name='최근 응답시간(ms)')),
                ('fail_count', models.IntegerField(default=0, verbose_name='연속 실패')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '모니터링 대상',
                'verbose_name_plural': '모니터링 대상',
                'db_table': 'monitor_targets',
                'ordering': ['group', 'host', 'port'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('down', 'Down'), ('cpu_over', 'CPU Over'), ('mem_over', 'Memory Over'), ('disk_over', 'Disk Over')], default='down', max_length=20, verbose_name='조건')),
                ('threshold', models.IntegerField(default=0, verbose_name='임계값')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=10, verbose_name='레벨')),
                ('consecutive', models.IntegerField(default=3, verbose_name='연속 실패 후 알림')),
                ('cooldown', models.IntegerField(default=300, verbose_name='재알림 방지(초)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='마지막 트리거')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='nms.monitortarget', verbose_name='대상')),
            ],
            options={
                'verbose_name': '알림 규칙',
                'verbose_name_plural': '알림 규칙',
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10, verbose_name='레벨')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시각')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='복구 시각')),
                ('fcm_result', models.CharField(blank=True, default='', max_length=500, verbose_name='FCM 결과')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='nms.alertrule', verbose_name='규칙')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nms.monitortarget', verbose_name='대상')),
            ],
            options={
                'verbose_name': '알림 이력',
                'verbose_name_plural': '알림 이력',
                'db_table': 'alerts',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('warn', 'Warning'), ('unknown', 'Unknown')], max_length=10, verbose_name='상태')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='응답시간(ms)')),
                ('detail', models.TextField(blank=True, default='', verbose_name='상세')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='nms.monitortarget', verbose_name='대상')),
            ],
            options={
                'verbose_name': '상태 로그',
                'verbose_name_plural': '상태 로그',
                'db_table': 'status_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target', '-created_at'], name='status_logs_target__87e40c_idx')],
            },
        ),
    ]
