# Generated by Django 5.1.15 on 2026-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='priority',
            field=models.CharField(choices=[('lg', 'Large'), ('md', 'Medium'), ('sm', 'Small')], default='sm', max_length=2, verbose_name='우선순위'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='group',
            field=models.CharField(choices=[('server', 'Server'), ('service', 'Service'), ('domain', 'Domain'), ('cctv', 'CCTV'), ('router', 'Router')], default='server', max_length=20, verbose_name='그룹'),
        ),
    ]
