# Generated by Django 5.1.15 on 2026-04-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0002_monitortarget_priority_alter_monitortarget_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='채널명')),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord')], max_length=20, verbose_name='채널 타입')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=200, verbose_name='봇 토큰')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Chat ID')),
                ('discord_webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Webhook URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '알림 채널',
                'verbose_name_plural': '알림 채널',
                'db_table': 'notification_channels',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, default='nms', max_length=50, verbose_name='소스'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nms.monitortarget', verbose_name='대상'),
        ),
        migrations.CreateModel(
            name='ChannelSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('min_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=10, verbose_name='최소 레벨')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='nms.monitortarget', verbose_name='대상')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='nms.notificationchannel', verbose_name='채널')),
            ],
            options={
                'verbose_name': '채널 구독',
                'verbose_name_plural': '채널 구독',
                'db_table': 'channel_subscriptions',
                'unique_together': {('channel', 'target')},
            },
        ),
    ]
