# Generated by Django 5.1.15 on 2026-04-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0003_notificationchannel_alert_source_alter_alert_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='날짜')),
                ('total_sales', models.BigIntegerField(default=0, verbose_name='총매출')),
                ('total_cost', models.BigIntegerField(default=0, verbose_name='총원가')),
                ('total_ad_cost', models.BigIntegerField(default=0, verbose_name='총광고비')),
                ('total_profit', models.BigIntegerField(default=0, verbose_name='총수익')),
                ('total_orders', models.IntegerField(default=0, verbose_name='총주문수')),
                ('markets_json', models.JSONField(default=dict, verbose_name='마켓별 데이터')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
            ],
            options={
                'verbose_name': '일일 매출 리포트',
                'db_table': 'daily_sales_report',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='check_type',
            field=models.CharField(choices=[('ping', 'Ping'), ('port', 'Port'), ('http', 'HTTP'), ('resource', 'Resource'), ('sms_device', 'SMS Device')], default='ping', max_length=20, verbose_name='체크 타입'),
        ),
    ]
