# Generated by Django 5.1.15 on 2026-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0004_dailysalesreport_alter_monitortarget_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='is_dev',
            field=models.BooleanField(default=False, verbose_name='개발중'),
        ),
    ]
